ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
WITH comCnt AS (
    SELECT c.ID, COUNT(p.ID) AS Количество
    FROM COMMUNITY c JOIN POSTS p ON p.COMMUNITY_ID = c.ID
    GROUP BY c.ID
), comCntMax AS (
    SELECT c.ID, MAX(Количество)
    FROM comCnt c
    GROUP BY c.ID
), comCntMin AS (
    SELECT c.ID, Min(Количество)
    FROM comCnt c
    GROUP BY c.ID
)
SELECT u.SURNAME, u.NAME, u.PATRONYMIC
FROM USERS u JOIN POSTS p ON p.CREATOR_ID = u.ID
WHERE (SELECT COUNT(*) FROM comCntMax c WHERE c.ID = p.COMMUNITY_ID) >= 2 AND
      (SELECT COUNT(*) FROM comCntMin c WHERE c.ID = p.COMMUNITY_ID) >= 2;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
WITH comCnt AS (
    SELECT c.ID, COUNT(p.ID) AS Количество
    FROM COMMUNITY c JOIN POSTS p ON p.COMMUNITY_ID = c.ID
    GROUP BY c.ID
), comCntMax AS (
    SELECT c.ID, MAX(Количество)
    FROM comCnt c
    GROUP BY c.ID
), comCntMin AS (
    SELECT c.ID, Min(Количество)
    FROM comCnt c
    GROUP BY c.ID
)
SELECT u.SURNAME, u.NAME, u.PATRONYMIC
FROM USERS u JOIN POSTS p ON p.CREATOR_ID = u.ID AND p.COMMUNITY_ID IN (SELECT ID FROM comCntMax) AND p.COMMUNITY_ID IN (SELECT ID FROM comCntMin)
GROUP BY u.SURNAME, u.NAME, u.PATRONYMIC, u.ID, p.COMMUNITY_ID
HAVING COUNT(*) >= 4 AND COUNT(DISTINCT p.COMMUNITY_ID) >= 2;