ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.USER_ID = u.ID AND f.STATUS = 3 AND f.FRIEND_ID = (SELECT u1.id FROM USERS u1 WHERE u1.LOGIN = 'i.i.ivanov')
UNION ALL
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.FRIEND_ID = u.ID AND f.STATUS = 3 AND f.USER_ID = (SELECT u1.id FROM USERS u1 WHERE u1.LOGIN = 'i.i.ivanov');

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
WITH id_ivanov AS (
    SELECT u.id, u.LOGIN
    FROM USERS u
    WHERE u.LOGIN = 'i.i.ivanov'
)
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.USER_ID = u.ID AND f.STATUS = 3 AND f.FRIEND_ID = (SELECT i.id FROM id_ivanov i)
UNION ALL
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.FRIEND_ID = u.ID AND f.STATUS = 3 AND f.USER_ID = (SELECT i.id FROM id_ivanov i );

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());