ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u
WHERE (EXTRACT(YEAR FROM current_date) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY)) > 18 AND
      (SELECT COUNT(*) FROM FRIENDS f WHERE f.STATUS = 3 AND (f.FRIEND_ID = u.ID OR f.USER_ID = u.ID)) >= 1;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM (SELECT u.id, u.SURNAME, u.NAME, u.PATRONYMIC
      FROM USERS u JOIN FRIENDS F on u.ID = F.USER_ID AND F.STATUS = 3
      WHERE (EXTRACT(YEAR FROM current_date) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY)) > 18
      UNION ALL
      SELECT u.id, u.SURNAME, u.NAME, u.PATRONYMIC
      FROM USERS u JOIN FRIENDS F on u.ID = F.FRIEND_ID AND F.STATUS = 3
      WHERE (EXTRACT(YEAR FROM current_date) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY)) > 18) u
GROUP BY u.ID, u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC
HAVING COUNT(*) >= 1;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());
