ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
SELECT u.LOGIN, c.NAME
FROM USERS u CROSS JOIN COMMUNITY c
             JOIN SUBSCRIBERS s ON s.USER_ID = u.ID
WHERE (SELECT COUNT(*) FROM FRIENDS f WHERE f.STATUS = 3 AND (f.USER_ID = u.ID OR f.FRIEND_ID = u.ID)) > 0;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
SELECT u.LOGIN, c.NAME
FROM USERS u CROSS JOIN COMMUNITY c
             JOIN FRIENDS F on (u.ID = F.USER_ID OR u.ID = F.FRIEND_ID) AND F.STATUS = 3
GROUP BY u.LOGIN, c.NAME
ORDER BY u.LOGIN;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());