BEGIN
    SYS.DBMS_STATS.DELETE_TABLE_STATS('MYUSER','USERS');
    SYS.DBMS_STATS.DELETE_TABLE_STATS('MYUSER','FRIENDS');
END;

SELECT TABLE_NAME, LAST_ANALYZED, NUM_ROWS, BLOCKS
FROM DBA_TABLES
WHERE TABLE_NAME IN ('USERS','FRIENDS')

ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
WITH id_ivanov AS (
    SELECT u.id, u.LOGIN
    FROM USERS u
    WHERE u.LOGIN = 'i.i.ivanov'
)
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.USER_ID = u.ID AND f.STATUS = 3 AND f.FRIEND_ID = (SELECT i.id FROM id_ivanov i)
UNION ALL
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.FRIEND_ID = u.ID AND f.STATUS = 3 AND f.USER_ID = (SELECT i.id FROM id_ivanov i );


SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

BEGIN
    SYS.DBMS_STATS.GATHER_TABLE_STATS('MYUSER','USERS');
    SYS.DBMS_STATS.GATHER_TABLE_STATS('MYUSER','FRIENDS');
END;

SELECT TABLE_NAME, LAST_ANALYZED, NUM_ROWS, BLOCKS
FROM DBA_TABLES
WHERE TABLE_NAME IN ('USERS','FRIENDS')

ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
WITH id_ivanov AS (
    SELECT u.id, u.LOGIN
    FROM USERS u
    WHERE u.LOGIN = 'i.i.ivanov'
)
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.USER_ID = u.ID AND f.STATUS = 3 AND f.FRIEND_ID = (SELECT i.id FROM id_ivanov i)
UNION ALL
SELECT u.SURNAME || ' ' || u.NAME || ' ' || u.PATRONYMIC as "ФИО"
FROM USERS u JOIN FRIENDS f ON f.FRIEND_ID = u.ID AND f.STATUS = 3 AND f.USER_ID = (SELECT i.id FROM id_ivanov i );

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

