ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH SHARED_POOL;

EXPLAIN PLAN FOR
WITH dialogs AS (
SELECT u.id, COUNT(DISTINCT m.PARTICIPANT_CHATROOM_USER_ID)
FROM USERS u JOIN PARTICIPANT_CHATROOM pc ON u.ID = pc.USER_ID
             JOIN Chatroom c ON pc.CHATROOM_ID = c.ID AND c.NAME = 'privateDialogue'
             JOIN MESSAGE m ON m.CHATROOM_ID = c.ID
WHERE (u.ID, PARTICIPANT_CHATROOM_USER_ID) IN (SELECT USER_ID, FRIEND_ID FROM FRIENDS)
      OR (PARTICIPANT_CHATROOM_USER_ID, u.ID) IN (SELECT USER_ID, FRIEND_ID FROM FRIENDS)
      OR PARTICIPANT_CHATROOM_USER_ID = u.ID
GROUP BY u.ID, pc.CHATROOM_ID
HAVING COUNT(m.PARTICIPANT_CHATROOM_USER_ID) >= 2
)
SELECT DISTINCT SURNAME || ' ' || NAME || ' ' || PATRONYMIC as ФИО
FROM users u JOIN dialogs o ON u.ID = o.ID;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

CREATE MATERIALIZED VIEW current_defect
ENABLE QUERY REWRITE
AS WITH dialogs AS (
SELECT u.id, COUNT(DISTINCT m.PARTICIPANT_CHATROOM_USER_ID)
FROM USERS u JOIN PARTICIPANT_CHATROOM pc ON u.ID = pc.USER_ID
             JOIN Chatroom c ON pc.CHATROOM_ID = c.ID AND c.NAME = 'privateDialogue'
             JOIN MESSAGE m ON m.CHATROOM_ID = c.ID
WHERE (u.ID, PARTICIPANT_CHATROOM_USER_ID) IN (SELECT USER_ID, FRIEND_ID FROM FRIENDS)
      OR (PARTICIPANT_CHATROOM_USER_ID, u.ID) IN (SELECT USER_ID, FRIEND_ID FROM FRIENDS)
      OR PARTICIPANT_CHATROOM_USER_ID = u.ID
GROUP BY u.ID, pc.CHATROOM_ID
HAVING COUNT(m.PARTICIPANT_CHATROOM_USER_ID) >= 2
)
SELECT DISTINCT SURNAME || ' ' || NAME || ' ' || PATRONYMIC as ФИО
FROM users u JOIN dialogs o ON u.ID = o.ID;

EXPLAIN PLAN FOR
WITH dialogs AS (
SELECT u.id, COUNT(DISTINCT m.PARTICIPANT_CHATROOM_USER_ID)
FROM USERS u JOIN PARTICIPANT_CHATROOM pc ON u.ID = pc.USER_ID
             JOIN Chatroom c ON pc.CHATROOM_ID = c.ID AND c.NAME = 'privateDialogue'
             JOIN MESSAGE m ON m.CHATROOM_ID = c.ID
WHERE (u.ID, PARTICIPANT_CHATROOM_USER_ID) IN (SELECT USER_ID, FRIEND_ID FROM FRIENDS)
      OR (PARTICIPANT_CHATROOM_USER_ID, u.ID) IN (SELECT USER_ID, FRIEND_ID FROM FRIENDS)
      OR PARTICIPANT_CHATROOM_USER_ID = u.ID
GROUP BY u.ID, pc.CHATROOM_ID
HAVING COUNT(m.PARTICIPANT_CHATROOM_USER_ID) >= 2
)
SELECT DISTINCT SURNAME || ' ' || NAME || ' ' || PATRONYMIC as ФИО
FROM users u JOIN dialogs o ON u.ID = o.ID;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

DROP MATERIALIZED VIEW current_defect;